import{a as g,S as P,i as a}from"./assets/vendor-9md0t_4N.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();g.defaults.baseURL="https://pixabay.com/api/";const R="51706817-4b5d2cc21e6cd3f5251979b08",y=15;async function p(o,i=1){try{const{data:t}=await g.get("",{params:{key:R,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:i,per_page:y}});return t}catch(t){throw t}}const u=document.querySelector(".gallery"),b=document.querySelector(".loader"),L=document.querySelector(".load-more");let d;function w(o=[],i=!1){const t=o.map(({webformatURL:s,largeImageURL:e,tags:r,likes:l,views:q,comments:M,downloads:S})=>`
      <div class="photo-card">
        <a class="gallery__item" href="${e}">
          <img class="gallery__image" src="${s}" alt="${r}" loading="lazy" />
        </a>
        <ul class="info">
          <li><b>Likes:</b> ${l}</li>
          <li><b>Views:</b> ${q}</li>
          <li><b>Comments:</b> ${M}</li>
          <li><b>Downloads:</b> ${S}</li>
        </ul>
      </div>`).join("");i?u.insertAdjacentHTML("beforeend",t):u.innerHTML=t,d?d.refresh():d=new P(".gallery a",{captionsData:"alt",captionDelay:250})}function $(){u.innerHTML=""}function v(){b.classList.remove("is-hidden")}function E(){b.classList.add("is-hidden")}function D(){L.classList.remove("is-hidden")}function f(){L.classList.add("is-hidden")}const _=document.querySelector("form"),B=document.querySelector(".load-more"),h=document.querySelector(".gallery");let c="",n=1,m=0;_.addEventListener("submit",async o=>{if(o.preventDefault(),c=(new FormData(o.currentTarget).get("searchText")||"").trim(),!c){a.error({position:"topRight",title:"Error",message:"Ви нічого не ввели!"});return}n=1,$(),f(),v();try{const{hits:t,totalHits:s}=await p(c,n);if(!t.length){a.error({position:"topRight",title:"Немає результатів",message:"Нічого не знайдено"});return}w(t,!1),m=Math.ceil(s/y),n<m?D():(f(),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(t){a.error({position:"topRight",title:"Помилка",message:t.message||t})}finally{E()}});B.addEventListener("click",async()=>{n+=1;try{v();const{hits:o}=await p(c,n);if(w(o,!0),h.firstElementChild){const i=h.firstElementChild,{height:t}=i.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}n>=m&&(f(),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(o){a.error({title:"Помилка",message:o.message||o,position:"topRight"})}finally{E()}});
//# sourceMappingURL=index.js.map
